name: Build and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # the Node.js versions to build on
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint the project
        run: pnpm nx run-many -t lint

      - name: Build the project
        run: pnpm nx run-many -t build

      - name: List, audit, fix outdated dependencies and build again
        run: |
          npm list --outdated
          pnpm audit || true  # ignore failures
          pnpm audit fix || true
          npm list --outdated
          pnpm nx run-many -t build

      - name: Publish to npm
        run: pnpm nx run-many -t nx-release-publish
